[tool.poetry]
name = "catpandoc"
version = "2020.2"
description = "Cat multiple document files to the terminal"
authors = ["FredHappyface"]
classifiers = [
	"Programming Language :: Python :: 3.5",
	"Programming Language :: Python :: 3.6",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Operating System :: OS Independent"
]
homepage = "https://github.com/FHPythonUtils/CatPandoc"
repository = "https://github.com/FHPythonUtils/CatPandoc"
documentation = "https://github.com/FHPythonUtils/CatPandoc/blob/master/README.md"
readme = "README.md"

[tool.poetry.scripts]
catpandoc = 'catpandoc.application:cli'

[tool.poetry.dependencies]
python = "^3.5"
art = "^4.6"
emoji = "^0.5.4"
pypandoc = "^1.5"
pygments = "^2.6.1"
catimage = "^2020.5"
cli2gui = "^2020.7"

[tool.dephell.main]
from = "pyproject.toml"
to = "requirements.txt"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
